spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
server:
  port: 8082

jwt:
  secret: ${JWT_SECRET}
  lifetime: 60m

telegram:
  username: ${TELEGRAM_USERNAME}
  token: ${TELEGRAM_TOKEN}

file:
  directory: ${FILE_DIRECTORY}