spring:
  datasource:
    url: jdbc:postgresql://postgres-db.ctoiwoqmopgw.eu-north-1.rds.amazonaws.com:5432/postgres
    username: postgres
    password: ptcyZG9-T9yciQa
    driver-class-name: org.postgresql.Driver
server:
  port: 8082

jwt:
  secret: 984hg493gh0439rthr0429uruj2309yh937gc763fe87t3f89723gf
  lifetime: 60m